config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'deals#index'

  resources :deals
  resources :deal_imports, only: [:index, :create] do
    post 'deals', on: :collection
  end
  resources :pipedrive_tokens, only: [:create]
  delete 'pipedrive_tokens', to: 'pipedrive_tokens#destroy'
end

app/controllers/deal_imports_controller.rb
class DealImportsController < ApplicationController
  before_action :authenticate_user!

  def index
    @pipedrive_token = session[:pipedrive_token]
    set_pipelines_and_owners
  end

  # lists deals for selecteed dropdown combos.
  # Sets values recieved from pipeline and owner dropdown combobox.
  def deals
    session[:pipeline] = JSON.parse(params[:pipeline]).except('selected')
    session[:owner] = JSON.parse(params[:owner]).except('selected')
    @pipedrive_token = session[:pipedrive_token]
    set_pipelines_and_owners

    resp = PipedriveCustom.new(session[:pipedrive_token]).deals_by_pipeline_and_owner(session[:pipeline]['id'], session[:owner]['id'])
    @pipedrive_deals = resp.success? ? resp.data : []
    respond_to do |format|
      format.js
    end
  end

  # uses pipedrive token and deal ids to fetch and store information of deals from pipedrive to application database.
  # Token and deal ids are fetched from session.
  def create
    resp = ImportPipedriveDeal.new(session[:pipedrive_token], params[:pipedrive_deals], current_user.id).call
    if resp.success?
      flash.now[:notice] = 'Deals Imported Successfully.'
    else
      flash.now[:error] = 'Deals Imported Successfully.'
    end
    respond_to do |format|
      format.js
    end
  end

  private

  def set_pipelines_and_owners
    resp = PipedriveCustom.new(@pipedrive_token).pipelines
    @pipelines = resp.success? ? resp.data : []
    resp = PipedriveCustom.new(@pipedrive_token).owners
    @owners = resp.success? ? resp.data : []
  end
end

app/helpers/deal_imports_helper.rb
module DealImportsHelper
end

app/views/deal_imports/_deals_table.html.erb
<%= form_with url: deal_imports_path, method: :post, :html => { :class => "form-horizontal deal_import" }, remote: true do |f| %>

<table class="table table-striped">
  <caption>Deals (For the Salesman Above):</caption>
  <thead class="thead-dark">
    <tr>
      <th>Select Deal</th>
      <th>Customer</th>
      <th>Title</th>
      <th>Value</th>
      <th>Status</th>
    </tr>
  </thead>
  <tbody>
    <% if @pipedrive_deals.present? %>
      <% @pipedrive_deals.each do |deal_hash| %>
        <tr>
          <td>
            <div class="form-check">
              <%= f.check_box 'pipedrive_deals', { multiple: true }, deal_hash['id'], nil %>              
            </div>
          </td>
          <td><%= deal_hash['org_name'] %></td>
          <td><%= deal_hash['title'] %></td>
          <td><%= deal_hash['value'] %></td>
          <td><%= deal_hash['status'] %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<div class="form-group">
  <div class="col-lg-10">
    <%= f.submit 'Import All Selected Deals', class: 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                deal_imports_path, :class => 'btn btn-default' %>
  </div>
</div>
<% end %>

app/views/deal_imports/_selection_form.html.erb
<%= form_with url: deals_deal_imports_path, :html => { :class => "form-horizontal deal_import" }, remote: true do |f| %>
  <% pipeline_name = session['pipeline'].present? ? session['pipeline']['name'] : nil %>
  <% owner_name = session['owner'].present? ? session['owner']['name'] : nil %>

  <div class="form-group">
    <%= label_tag :pipeline, "Pipeline", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= 
        f.select(
          :pipeline,
          @pipelines.map.with_index { |pipeline| [pipeline['name'], pipeline.to_json] },
          {
            selected: pipeline_name || false,
            include_blank: 'Select Pipeline'
          },
          { class: 'form-control pipeline_select', required: true }
        ) 
      %>
    </div>
    <%=f.error_span(:pipeline) %>
  </div>

  <div class="form-group">
    <%= label_tag :owner, "Owner", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= 
        f.select(
          :owner,
          @owners.map { |owner| [owner['name'], owner.to_json] },
          { 
            selected: owner_name || false,
            include_blank: 'Select Owner'
          },
          { class: 'form-control owner_select', required: true }
        )
      %>
    </div>
    <%=f.error_span(:owner) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit "Fetch Deals", :class => 'btn btn-primary' %>
    </div>
  </div>

<% end %>

<script>
  var pipeline_selected = false;
  var owner_selected = false;
  $('.pipeline_select').on('change', function(){
    pipeline_selected = $('.pipeline_select').val() != ""
    if(pipeline_selected && owner_selected){

    }
  })

  $('.owner_select').on('change', function(){
    owner_selected = $('.owner_select').val() != ""
  })
</script>

app/views/deal_imports/create.js.erb
$('.deal_import_table_form').html('<%= j render partial: "deals_table" %>');

app/views/deal_imports/deals.js.erb
$('.deal_import_table_form').html('<%= j render partial: "deals_table" %>');

app/views/deal_imports/index.html.erb
<h2>Import Deals from Pipedrive</h2>

<div class="pipedrive_connect_form">
  <%= render partial: 'pipedrive_tokens/form' %>
</div>

<div class="deal_import_selection_form">
  <%= render partial: 'selection_form' %>
</div>

<div class="deal_import_table_form">
  <%= render partial: 'deals_table' %>
</div>