config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'deals#index'

  resources :deals
  resources :deal_imports, only: [:index, :create] do
    post 'deals', on: :collection
  end
  resources :pipedrive_tokens, only: [:create]
  delete 'pipedrive_tokens', to: 'pipedrive_tokens#destroy'
end

app/models/deal.rb
class Deal < ApplicationRecord
  # associations
  belongs_to :created_by, class_name: 'User'
  belongs_to :user, optional: true

  # attributes
  enum status: [:won, :lost, :pending]

  # validations
  validates :status, :value, :customer, :title, presence: true
  validates :value, numericality: { greater_than_or_equal_to: 0 }
  validates :weighted_value, numericality: { greater_than_or_equal_to: 0, allow_nil: true }

  accepts_nested_attributes_for :created_by, allow_destroy: true, reject_if: proc { |attributes| attributes['name'].blank? }

  # scopes and class methods
  scope :by_user_id, ->(user_id) { where(created_by: user_id) }
end

app/controllers/deals_controller.rb
class DealsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_deal, only: [:show, :edit, :update, :destroy]
  before_action :fetch_deals, only: [:index, :create, :update, :destroy]
  rescue_from ActiveRecord::RecordNotFound, with: :record_not_found_handler

  def index
    build_deal
  end

  def show
  end

  def new
    build_deal
  end

  def edit
  end

  def create
    @deal = Deal.new(deal_params)
    if @deal.save
      build_deal
      flash.now[:notice] = 'Deal was successfully created.'
      respond_to do |format|
        format.html { redirect_to @deal }
        format.js
      end
    else
      build_deal
      flash.now[:error] = 'Deal could not be created.'
      respond_to do |format|
        format.html { render :new }
        format.js
      end
    end
  end

  def update
    if @deal.update(deal_params)
      build_deal
      flash.now[:notice] = 'Deal Updated successfully.'
      respond_to do |format|
        format.html { redirect_to @deal }
        format.js
      end
    else
      build_deal
      flash.now[:error] = 'Deal could not be updated.'
      respond_to do |format|
        format.html { render :edit }
        format.js
      end
    end
  end

  def destroy
    @deal.destroy
    build_deal
    respond_to do |format|
      format.html { redirect_to deals_url, notice: 'Deal was successfully destroyed.' }
      format.js
    end
  end

  private

  def set_deal
    @deal = Deal.find(params[:id])
  end

  def deal_params
    params.require(:deal).permit(:id, :title, :customer, :status, :value, :expected_closing_date, :created_by_id)
  end

  def fetch_deals
    @q = Deal.by_user_id(current_user.id).ransack(params[:q])
    @q.sorts = 'created_at desc' if @q.sorts.empty?
    @deals = @q.result(distinct: true).page(params[:page])
  end

  def build_deal
    @deal = Deal.new(created_by_id: current_user.id, user_id: current_user.id)
  end

  def record_not_found_handler
    respond_to do |format|
      format.html { render :index }
    end
  end
end

app/helpers/deals_helper.rb
module DealsHelper
end

app/views/deals/_deal_listing.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h3>Deal Listing</h3>
</div>
<%= search_form_for @q, :html => { :class => "form-inline" }, remote: true do |f| %>

  <div class="form-group">
    <%= f.label :search, :class => 'sr-only' %>
    <%= f.search_field :title_or_customer_cont, :class => 'form-control' %>
  </div>
  
  <%= f.submit nil, class: 'btn btn-primary' %>
<% end %>

<table class="table table-striped">
    <thead>
      <tr>
        <th><%= sort_link(@q, :id, model_class.human_attribute_name(:id), {}, { :remote => true, method: :get }) %></th>
        <th><%= sort_link(@q, :customer, model_class.human_attribute_name(:customer), {}, { remote: true, method: :get }) %></th>
        <th><%= sort_link(@q, :title, model_class.human_attribute_name(:title), {}, { remote: true, method: :get }) %></th>
        <th><%= sort_link(@q, :status, model_class.human_attribute_name(:status), {}, { remote: true, method: :get }) %></th>
        <th><%= sort_link(@q, :expected_closing_date, model_class.human_attribute_name(:expected_closing_date), {}, { remote: true, method: :get }) %></th>
        <th><%= sort_link(@q, :value, model_class.human_attribute_name(:value), {}, { remote: true, method: :get }) %></th>        
        <th><%=t '.actions', :default => t("helpers.actions") %></th>
      </tr>
    </thead>
    <tbody>
      <% if @deals.present? %>
      <% @deals.each do |deal| %>
        <tr>
          <td><%= link_to deal.id, deal_path(deal) %></td>
          <td><%= deal.customer %></td>
          <td><%= deal.title %></td>
          <td><%= deal.status %></td>
          <td><%= deal.expected_closing_date %></td>          
          <td><%= "#{deal.value} $" %></td>
          <td>
            <%= link_to t('.show', :default => t("helpers.links.show")),
                        deal_path(deal), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.edit', :default => t("helpers.links.edit")),
                        edit_deal_path(deal), :class => 'btn btn-default btn-xs' %>
            <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                        deal_path(deal),
                        :method => :delete,
                        remote: true,
                        :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                        :class => 'btn btn-xs btn-danger' %>
            <%= link_to t('.won', default: t('helpers.links.won')),
                        deal_path(deal, deal: { status: :won } ),
                        method: :put,
                        remote: true,
                        disabled: deal.status == 'won',
                        class: 'btn btn-xs btn-success' %>
            <%= link_to t('.lost', default: t('helpers.links.lost')),
                        deal_path(deal, deal: { status: :lost } ),
                        method: :put,
                        remote: true,
                        disabled: deal.status == 'lost',
                        class: 'btn btn-xs btn-danger' %>
          </td>
        </tr>
      <% end %>
      <% end %>
    </tbody>
  </table>
  <%= paginate @deals, remote: true %>

app/views/deals/_edit_form.html.erb
<%= form_for @deal, :html => { :class => "form-horizontal deal deal_form_for" } do |f| %>

  <% if @deal.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @deal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.hidden_field :created_by_id, value: @deal.created_by_id %>

  <div class="form-group">
    <%= f.label :customer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :customer, :class => 'form-control', required: true %>
    </div>
    <%=f.error_span(:customer) %> 
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control', required: true %>
    </div>
    <%=f.error_span(:customer) %> 
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :status, Deal.statuses.keys.map{ |key| [key.humanize, key] }, :class => 'form-control', required: true %>
    </div>
    <%=f.error_span(:status) %> 
  </div>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :value, :class => 'form-control', required: true, min: 1, max: 9999999 %>
    </div>
    <%=f.error_span(:value) %>
  </div>
  <div class="form-group">
    <%= f.label :expected_closing_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :expected_closing_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:expected_closing_date) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                deals_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/deals/_form.html.erb
<%= form_for @deal, :html => { :class => "form-horizontal deal deal_form_for" }, remote: true do |f| %>

  <% if @deal.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@deal.errors.count, "error") %> prohibited this deal from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @deal.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <%= f.hidden_field :created_by_id, value: @deal.created_by_id %>

  <div class="form-group">
    <%= f.label :customer, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :customer, :class => 'form-control', required: true %>
    </div>
    <%=f.error_span(:customer) %> 
  </div>
  <div class="form-group">
    <%= f.label :title, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, :class => 'form-control', required: true %>
    </div>
    <%=f.error_span(:customer) %> 
  </div>
  <div class="form-group">
    <%= f.label :status, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.select :status, Deal.statuses.keys.map{ |key| [key.humanize, key] }, :class => 'form-control', required: true %>
    </div>
    <%=f.error_span(:status) %> 
  </div>
  <div class="form-group">
    <%= f.label :value, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.number_field :value, :class => 'form-control', required: true, min: 1, max: 9999999 %>
    </div>
    <%=f.error_span(:value) %>
  </div>
  <div class="form-group">
    <%= f.label :expected_closing_date, :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.date_field :expected_closing_date, :class => 'form-control' %>
    </div>
    <%=f.error_span(:expected_closing_date) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, :class => 'btn btn-primary' %>
      <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                deals_path, :class => 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/deals/create.js.erb
$('.deal_listing_table').html('<%= j render partial: "deal_listing" %>');
$('.deal_form').html('<%= j render partial: "form" %>');

app/views/deals/destroy.js.erb
$('.deal_listing_table').html('<%= j render partial: "deal_listing" %>');

app/views/deals/edit.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'edit_form' %>

app/views/deals/index.html.erb
<div class="page-header">
  <h3>New Deal</h3>
</div>

<div class="deal_form">
  <%= render :partial => 'form' %>
</div>

<div class="import_deals">
  <%= link_to 'Import Deals', deal_imports_path, class: 'btn btn-success' %>
</div>

<div class="deal_listing_table">
  <%= render :partial => 'deal_listing' %>
</div>

app/views/deals/index.js.erb
$('.deal_listing_table').html('<%= j render partial: "deal_listing" %>');

app/views/deals/new.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/deals/show.html.erb
<%- model_class = Deal -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:customer) %>:</strong></dt>
  <dd><%= @deal.customer %></dd>
  <dt><strong><%= model_class.human_attribute_name(:status) %>:</strong></dt>
  <dd><%= @deal.status %></dd>
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @deal.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:value) %>:</strong></dt>
  <dd><%= @deal.value %></dd>
  <dt><strong><%= model_class.human_attribute_name(:expected_closing_date) %>:</strong></dt>
  <dd><%= @deal.expected_closing_date %></dd>
  <dt><strong><%= model_class.human_attribute_name(:created_by) %>:</strong></dt>
  <dd><%= @deal.created_by&.name %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              deals_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_deal_path(@deal), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              deal_path(@deal),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>

app/views/deals/update.js.erb
$('.deal_listing_table').html('<%= j render partial: "deal_listing" %>');
$('.deal_form').html('<%= j render partial: "form" %>');