config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'deals#index'

  resources :deals
  resources :deal_imports, only: [:index, :create] do
    post 'deals', on: :collection
  end
  resources :pipedrive_tokens, only: [:create]
  delete 'pipedrive_tokens', to: 'pipedrive_tokens#destroy'
end

app/controllers/pipedrive_tokens_controller.rb
class PipedriveTokensController < ApplicationController
  before_action :authenticate_user!

  # Connects to pipedrive and stores the token in session.
  def create
    connection_information = PipedriveCustom.new(token_params[:token]).connection_information

    if connection_information.present?
      session[:pipedrive_token] = token_params[:token]
      @pipedrive_token = token_params[:token]
      list_pipelines_and_owners
      respond_to do |format|
        format.js { flash.now[:notice] = 'Connected to Pipedrive successfully!' }
      end
    else
      session[:pipedrive_token] = nil
      @pipedrive_token = nil
      list_empty_pipelines_and_owners
      respond_to do |format|
        format.js { flash.now[:error] = 'Could not connect to Pipedrive.' }
      end
    end
  end

  # Removes the token from session.
  def destroy
    session[:pipedrive_token] = nil
    @pipedrive_token = nil
    flash.now[:success] = 'Disconnected'
    list_empty_pipelines_and_owners
    respond_to do |format|
      format.js
    end
  end

  private

  def token_params
    params.permit(:token)
  end

  def fetch_token
    @pipedrive_token = current_user.pipedrive_token || current_user.build_pipedrive_token
  end

  def list_pipelines_and_owners
    resp = PipedriveCustom.new(session[:pipedrive_token]).pipelines
    @pipelines = resp.success? ? resp.data : []
    resp = PipedriveCustom.new(session[:pipedrive_token]).owners
    @owners = resp.success? ? resp.data : []
  end

  def list_empty_pipelines_and_owners
    @pipelines = []
    @owners = []
  end
end

app/helpers/pipedrive_tokens_helper.rb
module PipedriveTokensHelper
end

app/views/pipedrive_tokens/_form.html.erb
<% if @pipedrive_token.present? %>
 <% form_for_method = :delete %>
 <% submit_button_name = 'Disconnect' %>
<% else %>
  <% form_for_method = :post %>
  <% submit_button_name = 'Connect' %>
<% end %>

<%= form_with url: pipedrive_tokens_path, method: form_for_method, :html => { :class => "form-horizontal pipedrive_token_form" }, remote: true do |f| %>
  <div class="form-group">
    <%= f.label_tag :token, "Pipedrive Token", :class => 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :token, value: @pipedrive_token, class: 'form-control', required: true %>
    </div>
  </div>


  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-2">
      <%= f.submit submit_button_name, :class => 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/pipedrive_tokens/create.js.erb
$('.flash_message').html("<%= j render partial: 'shared/flash_messages' %>")
$('.pipedrive_connect_form').html("<%= j render partial: 'pipedrive_tokens/form' %>")
$('.deal_import_selection_form').html("<%= j render partial: 'deal_imports/selection_form' %>");

app/views/pipedrive_tokens/destroy.js.erb
$('.flash_message').html("<%= j render partial: 'shared/flash_messages' %>")
$('.pipedrive_connect_form').html("<%= j render partial: 'pipedrive_tokens/form' %>")
$('.deal_import_selection_form').html("<%= j render partial: 'deal_imports/selection_form' %>");